//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int CardsID { get; set; }
        public int ChargeAccountTypeID { get; set; }
        public string CardNumber { get; set; }
        public string CardPassWord { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> ReChargeStatus { get; set; }
        public string ReChargeMsg { get; set; }
        public bool IsAvailable { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public Nullable<System.DateTime> UseTime { get; set; }
    }
}
