//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeClass
    {
        public int ChargeClassID { get; set; }
        public string ChargeClassName { get; set; }
        public string Descrtion { get; set; }
        public string QueryClassName { get; set; }
    }
}
