//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeClass
    {
        public int ChargeClassID { get; set; }
        public string ChargeClassName { get; set; }
        public string Descrtion { get; set; }
        public string QueryClassName { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
