//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeClassInfo
    {
        public int ChargeClassInfoID { get; set; }
        public int ChargeClassID { get; set; }
        public string ResultInfo { get; set; }
        public string OrderStatus { get; set; }
    }
}
