//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCLEntities : DbContext
    {
        public DCLEntities()
            : base("name=DCLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<ChargeAccountType> ChargeAccountType { get; set; }
        public virtual DbSet<ChargeClass> ChargeClass { get; set; }
        public virtual DbSet<ClientConfig> ClientConfig { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderChargeAccount> OrderChargeAccount { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ChargeClassInfo> ChargeClassInfo { get; set; }
        public virtual DbSet<ProductInfo> ProductInfo { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
