//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderChargeAccount
    {
        public int OrderChargeAccountID { get; set; }
        public int ChargeAccountTypeID { get; set; }
        public string ChargeAccount { get; set; }
        public string ChargePassword { get; set; }
        public string PayPassword { get; set; }
        public Nullable<int> ParValue { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> UseTimes { get; set; }
        public Nullable<bool> IsUsing { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUseTime { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    }
}
