//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderChargeAccount
    {
        public int OrderChargeAccountID { get; set; }
        public int ChargeAccountTypeID { get; set; }
        public string ChargeAccount { get; set; }
        public string ChargePassword { get; set; }
        public string PayPassword { get; set; }
        public Nullable<int> ParValue { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> UseTimes { get; set; }
        public Nullable<bool> IsUsing { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUseTime { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    }
}
