//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public int ProductInfoID { get; set; }
        public int ProductID { get; set; }
        public string GameName { get; set; }
        public string GameValue { get; set; }
        public string ServerName { get; set; }
        public string ServerValue { get; set; }
        public string AreaName { get; set; }
        public string AreaValue { get; set; }
    }
}
