//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public int ProductInfoID { get; set; }
        public int ProductID { get; set; }
        public string GameName { get; set; }
        public string GameValue { get; set; }
        public string ServerName { get; set; }
        public string ServerValue { get; set; }
        public string AreaName { get; set; }
        public string AreaValue { get; set; }
    }
}
