//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public int ChargeClassID { get; set; }
        public string ProductCode { get; set; }
        public string Descrtion { get; set; }
        public bool IsActive { get; set; }
        public string MerchantCode { get; set; }
        public string ChargeClassProductCode { get; set; }
    }
}
